server:
  port: 8787
  servlet:
    context-path: /kafka

#spring:
#  application:
#    name: kafka-server
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.cj.jdbc.Driver
#    druid:
#        # 主库数据源
#      master:
#        url: jdbc:mysql://192.168.11.4:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#        username: root
#        password: 1234
#        # 从库数据源
#      slave:
#          # 从数据源开关/默认关闭
#        enabled: false
#        url:
#        username:
#        password:
#  redis:
#    host: localhost
#    port: 6379
#    password:


logging:
  level:
    com.example: debug
    org.springframework: info
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
mybatis:
  type-aliases-package: com.example.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# message相关配置
#spring:
#  kafka:
#    bootstrap-servers: localhost:8788
spring:
  rabbitmq:
    host: localhost
    port: 8550
    username: root
    password: 123456
    virtual-host: /


mq:
  routingKey: TestDirectRouting
  directExchange: directExchange
