server:
  port: 8786
  servlet:
    context-path: /xiaoheihe

spring:
  application:
    name: xiaoheihe
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
        # 主库数据源
      master:
        url: jdbc:mysql://192.168.11.4:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 1234
        # 从库数据源
      slave:
          # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
  redis:
    host: localhost
    port: 6379
    password:
    database: 10


    login:
      token:
        prefix: REDIS_LOGIN_TOKEN_
        timeout: 60
        timeunit: SECONDS
logging:
  level:
    com.example: debug
    org.springframework: info
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
  file:
    name: log.log
mybatis:
  type-aliases-package: com.example.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml


mq:
  routingKey: TestDirectRouting
  directExchange: directExchange

rsa:
  key:
    pubKeyFile: /config/auth_key/id_key_rsa.pub
    priKeyFile: /config/auth_key/id_key_rsa

securityUrlConfig:
  ignoreUrl: "/login.jsp,/failuer.jsp,/css/**,/img/**"


oss:
  accessKeyId: LTAIiFezBad57uXs
  accessKeySecret: yWhTGpXIAnPLkrMbsDNZBJOezFfCvF
  endpoint: https://oss-cn-shanghai.aliyuncs.com
  bucketName: yanxiaoneng
  url: https://yanxiaoneng.oss-cn-shanghai.aliyuncs.com/
  filePath: safety_tool/templates
